INSERT INTO book (title, author, cover, description) VALUES ('I Am Enough', 'Marisa Peer', 'https://m.media-amazon.com/images/I/41JqDfAJaBL._SX260_.jpg', 'I Am Enough has been written in a style that is designed to change you from the inside out. It changes you on a personal level using Marisa Peers proven techniques to make a deep and lasting impact on how you feel about you and how others feel about you. Marisa has been a leading therapist for over 30 years and had developed her own method of therapy called Rapid Transformational Therapy that has won numerous awards because of its effectiveness. Many of her most effective techniques and methods are contained within this book. The powerful wording and cutting-edge techniques inside this book, enable you to achieve powerful and recognizable results rapidly and permanently. Marisa is passionate about helping people to change using simple techniques that have powerful results and now you can use them to change your life.');
INSERT INTO book (title, author, cover, description) VALUES ('The Coaching Habit: Say Less, Ask More & Change the Way You Lead Forever', 'Michael Bungay Stanier', 'https://www.delfi.rs/_img/artikli/2020/12/the_coaching_habit_say_less_ask_more_change_the_way_your_lead_forever_vv.jpg', 'In Michael Bungay Stanier''s The Coaching Habit, coaching becomes a regular, informal part of your day so managers and their teams can wok less hard and have more impact. Drawing on years of experience training more than 10,000 busy managers from around the globe in practical, everyday coaching skills, Bungay Stanier reveals how to unlock your peoples potential. He unpacks seven essential coaching questions to demonstrate how--by saying less and asking more--you can develop coaching methods that produce great results.');
INSERT INTO book (title, author, cover, description) VALUES ('Apache Solr 3.1 Cookbook', 'Rafał Kuć', 'https://m.media-amazon.com/images/P/1849512183.01._SCLZZZZZZZ_SX500_.jpg', 'This book is part of Packt''s Cookbook series; each chapter looks at a different aspect of working with Apache Solr. The recipes deal with common problems of working with Solr by using easy-to-understand, real-life examples. The book is not in any way a complete Apache Solr reference and you should see it as a helping hand when things get rough on your journey with Apache Solr.Developers who are working with Apache Solr and would like to know how to combat common problems will find this book of great use. Knowledge of Apache Lucene would be a bonus but is not required.');
INSERT INTO book (title, author, cover, description) VALUES ('DBA''s Guide to NoSQL: Apache Cassandra', 'The Enlightened DBA', 'https://imgv2-1-f.scribdassets.com/img/word_document/241642040/original/216x287/fced5b0eb0/1632324924?v=1', 'For the new or veteran DBA: Whether you''re skeptical or enthusiastic about new types of databases this book contains all you need to understand about when and how to implement NoSQL technology in your Cloud Applications. In this guide, you''ll get answers to these questions and more; you''ll learn exactly what NoSQL is, why it''s needed, how it works, and when it should (and shouldn''t) be used.');
INSERT INTO book (title, author, cover, description) VALUES ('Migrating to Cloud-Native Application Architectures', 'Matt Stine', 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1429085863i/25363309._UY475_SS475_.jpg', 'Author Matt Stine also examines the cultural, organizational, and technical changes necessary to migrate traditional monolithic applications and service-oriented architectures to cloud-native architectures. You’ll also find a Migration Cookbook, with recipes for decomposing monolithic applications into microservices, implementing fault-tolerant patterns, and performing automated testing of cloud-native services.');
INSERT INTO book (title, author, cover, description) VALUES ('Effective Java (2nd Edition)', 'Joshua Bloch', 'https://kbimages1-a.akamaihd.net/f6934e40-ef89-4833-af6d-4fe1b63b31dc/1200/1200/False/effective-java-2.jpg', 'Are you looking for a deeper understanding of the Java™ programming language so that you can write code that is clearer, more correct, more robust, and more reusable? Look no further! Effective Java™, Second Edition, brings together seventy-eight indispensable programmer’s rules of thumb: working, best-practice solutions for the programming challenges you encounter every day. This highly anticipated new edition of the classic, Jolt Award-winning work has been thoroughly updated to cover Java SE 5 and Java SE 6 features introduced since the first edition. Bloch explores new design patterns and language idioms, showing you how to make the most of features ranging from generics to enums, annotations to autoboxing. Each chapter in the book consists of several “items” presented in the form of a short, standalone essay that provides specific advice, insight into Java platform subtleties, and outstanding code examples. The comprehensive descriptions and explanations for each item illuminate what to do, what not to do, and why.');
INSERT INTO book (title, author, cover, description) VALUES ('Professional Android 4 Application Development', 'Reto Meier', 'https://media.wiley.com/product_data/coverImage300/58/11182621/1118262158.jpg', 'The fast-growing popularity of Android smartphones and tablets creates a huge opportunities for developers. If you''re an experienced developer, you can start creating robust mobile Android apps right away with this professional guide to Android 4 application development. Written by one of Google''s lead Android developer advocates, this practical book walks you through a series of hands-on projects that illustrate the features of the Android SDK. That includes all the new APIs introduced in Android 3 and 4, including building for tablets, using the Action Bar, Wi-Fi Direct, NFC Beam, and more.');

INSERT into book_topic (book_id, topic_id) VALUES (80,5);
INSERT into book_topic (book_id, topic_id) VALUES (81,5);
INSERT into book_topic (book_id, topic_id) VALUES (81,2);
INSERT into book_topic (book_id, topic_id) VALUES (82,1);
INSERT into book_topic (book_id, topic_id) VALUES (83,1);
INSERT into book_topic (book_id, topic_id) VALUES (84,1);
INSERT into book_topic (book_id, topic_id) VALUES (85,1);
INSERT into book_topic (book_id, topic_id) VALUES (86,1);